# Generated by Django 3.0.7 on 2020-06-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionplanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='SportsSession',
        ),
    ]
