# Generated by Django 3.0.7 on 2020-06-13 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessionplanner', '0002_auto_20200613_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportssession',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='sports_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionplanner.SportsSession'),
            preserve_default=False,
        ),
    ]
