# Generated by Django 3.0.7 on 2020-06-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionplanner', '0003_auto_20200613_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sports_session',
        ),
        migrations.AddField(
            model_name='sportssession',
            name='sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessionplanner.Section'),
        ),
    ]
