# Generated by Django 3.0.7 on 2020-06-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionplanner', '0005_remove_sportssession_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sports_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessionplanner.SportsSession'),
        ),
    ]
