# Generated by Django 3.0.7 on 2020-06-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionplanner', '0007_sportssession_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sports_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='sessionplanner.SportsSession'),
        ),
    ]
