# Generated by Django 3.0.7 on 2020-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200616_1253'),
        ('sessionplanner', '0008_auto_20200616_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='game',
            field=models.ManyToManyField(to='games.Game'),
        ),
    ]
