# Generated by Django 3.0.7 on 2020-06-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200616_1253'),
        ('sessionplanner', '0009_section_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='game',
        ),
        migrations.AddField(
            model_name='section',
            name='game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
