# Generated by Django 3.0.7 on 2020-06-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='max_number_players',
            new_name='max_num_players',
        ),
    ]
