# Generated by Django 3.0.7 on 2020-07-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200616_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coach_to_player_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='difficult_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='max_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='num_footballs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='phys_focus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='physical_fitness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='playing_fact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tactical_prowess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tech_prof_block',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tech_prof_body_catch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tech_prof_hand_pass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tech_prof_hook_kick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tech_prof_near_hand_tackle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tech_prof_pick_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='tech_prof_punt_kick',
            field=models.IntegerField(default=0),
        ),
    ]
