# Generated by Django 3.0.7 on 2020-07-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200705_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='playing_fact',
            new_name='playing_facts',
        ),
    ]
